- name : Elasticsearch app configuration 
  hosts : elasticSearch_server
  become : yes
  # vars:
  #   ansible_connection: aws_ssm
  #   ansible_aws_ssm_bucket_name: elk-private
  #   ansible_aws_ssm_region: eu-central-1
  #   ansible_aws_ssm_instance_id : i-0f790f85b57e349da

   #plugin: community.aws.aws_ssm

  tasks:
    - name: Update repositories cache and install Java
      apt:
        name: default-jre
        update_cache: yes

    - name: Update repositories cache and install apt-transport-https
      apt:
        name: apt-transport-https
        update_cache: yes
    
    - name: Update repositories cache and install Openssl
      apt:
        name: openssl
        update_cache: yes


    #install ElasticSearch
    - name: Import the Elastic Key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - name: Adding Elastic APT repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
        state: present
        filename: elastic-8.x.list
        update_cache: yes
    - name: install elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes
    - name: reload systemd config
      systemd: daemon_reload=yes
    - name: enable service elasticsearch and ensure it is not masked
      systemd:
        name: elasticsearch
        enabled: yes
        masked: no
    - name: ensure elasticsearch is running
      systemd: state=started name=elasticsearch

    #configure file
    - name: Configure elasticsearch.yml File
      copy:
        src: ./elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
    
    #Change the ownership
    #- name: set elasticsearch permissions
    #  file:
    #    path: /usr/share/elasticsearch
    #    state: directory
    #    recurse: yes
    #   owner: elasticsearch
    #    group: elasticsearch

    #

    #ElasticSearch start
    - name: restart elasticsearch after change configuration by configure-elastic-file role
      systemd:
        state: restarted
        daemon_reload: yes
        name: elasticsearch
    - name: ensure elasticsearch is running
      systemd:
        state=started
        name=elasticsearch


